### ISSUE TITLE
Add a Move command

### ISSUE THREAD

**Issue by skinkwork** [m-hall/HypnotoadSVN#12]
It would be great if either the **Rename** command included the ability to change the file's path, or a new **Move** command was added to allow moving files & folders using _svn move_.

**Comment by m-hall** [comment]
You should be able to do this by adding path information before the filename.
eg.
../example.txt
another/example.txt

I do take your point though; it might make sense to add a move command that includes the whole path in the operation.

**Comment by skinkwork** [comment]
Thank you for the quick response - if I get a chance I'll fork the repo and add a Move command, until then I'll use relative paths.

**Comment by m-hall** [comment]
A move command has been added in 1.4.0
