### ISSUE TITLE
AttributeError: 'HypnoSvnCommitCommand' object has no attribute 'get_svn_path'

### ISSUE THREAD

**Issue by matthieusieben** [m-hall/HypnotoadSVN#14]
Hi,
I recently started to use this (great) plugin.
Yesterday, without changing anything (no manual installation/configuration of any other plugin) HypnotoadSVN stopped working. I see the following content in the console after trying to open the SVN menu from the side bar:

http://pastebin.com/BR5Cxhpt
Any idea what might me going on?

**Comment by m-hall** [comment]
I apologize very much; it seems that when I added the svnPath I renamed a function right before committing, and didn't re-test. It should be fixed with 1.4.2. I promise I tested this time.

**Comment by matthieusieben** [comment]
Ha, programmers and their refactoring mania...
Thanks for the fast response. Cheers
