### ISSUE TITLE
Checkout from ST3

### ISSUE THREAD

**Issue by GuillaumeBibaut** [m-hall/HypnotoadSVN#2]
It seems I'm having some problems to checkout from ST3 on a project with a folder in it.
Basically, I've created a folder on my account and then I've added it to a project in ST3. Then I've right-clicked the folder in ST3 and then choose "Checkout" in the HypnotoadSVN "SVN" sub menu. The input panel appears and I enter a valid SVN URI that I can checkout from the command line in a Terminal (but I don't want to use it this way)
When I enter any URL in the input panel, I'm getting these messages :

```
Command: Checkout
    svn checkout --non-interactive "/Users/user1/svn/testtest"
    Files:
        /Users/user1/svn/testtest
    Output:
    Error: 1
        svn: E205000: Try 'svn help' for more info
        svn: E205000: Error parsing arguments

    Completed
```

And also I can see in the console these messages :

```
HypnotoadSVN: Checkout
HypnotoadSVN: svn checkout --non-interactive "/Users/user1/svn/testtest"
HypnotoadSVN: svn checkout --non-interactive "/Users/user1/svn/testtest" DONE
```

The Python version installed (by default ?) on my OSX computer is 2.7.6

**Comment by m-hall** [comment]
Issue should be fixed in 1.2.3.
Sorry about that!
